#!/bin/bash

# Quick Database Setup Script for RosterXPro
# This script will guide you through setting up your Supabase database

echo "🚀 RosterXPro Database Setup"
echo "=========================================="
echo ""
echo "You need to run the SQL script in your Supabase dashboard."
echo ""
echo "Step 1: Open your Supabase dashboard"
echo "URL: https://supabase.com/dashboard/project/zztaqvbmsjhftnyreabz"
echo ""
echo "Step 2: Go to Database → SQL Editor"
echo ""
echo "Step 3: Copy and paste the entire content of setup-database.sql"
echo ""
echo "Step 4: Click 'Run' button"
echo ""
echo "Expected output:"
echo "- Table 'user_profiles' created successfully"
echo "- RLS policies created (4 policies)"
echo "- Indexes created for performance"
echo "- Trigger for updated_at column"
echo ""
echo "Step 5: Create storage bucket"
echo "- Go to Storage"
echo "- Create bucket: 'profile-images'"
echo "- Set as Public: true"
echo ""
echo "Step 6: Copy and paste content of setup-storage-policies.sql"
echo "- Go to Storage → Policies"
echo "- Run each policy statement"
echo ""
echo "After completing these steps, your registration should work properly!"
echo ""
echo "🔧 Troubleshooting:"
echo "If you get errors, check:"
echo "1. Database table exists: SELECT * FROM user_profiles LIMIT 1;"
echo "2. RLS is enabled: SELECT rowsecurity FROM pg_tables WHERE tablename = 'user_profiles';"
echo "3. Policies exist: SELECT * FROM pg_policies WHERE tablename = 'user_profiles';"
echo ""
echo "Need help? Check the detailed setup guide in SUPABASE_SETUP.md"
